### ISSUE TITLE
not working after 08/12/20 update

### ISSUE THREAD

**Issue by charlee-dev** [70RMUND/Tormund-BFV-Radar#10]
`pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[+] Tormund's External Radar v1.3 for Battlefield V (Fall Update 2020) - Nov 18, 2020)
[+] Searching for BFV.exe...
[+] BFV.exe found, Handle: 0x280
[+] Gathering offsets, please wait...
[+] Starting Radar...
[+] Done
[+] Searching for ObfuscationMgr...

`

**Comment by charlee-dev** [comment]
offsets["OBFUS_MGR_PTR_1"]                 = 0x1438B46D0
offsets["OBFUS_MGR_RET_1"]                 = 0x147E207B6
offsets["OBFUS_MGR_DEC_FUNC"]              = 0x14161F880
offsets["OBJECTIVE_VTBL"]                  = 0x1437A7EF8

**Comment by DJPatron** [comment]
> offsets["OBFUS_MGR_PTR_1"] = 0x1438B46D0

```
C:\Program Files (x86)\Origin Games\radar>python radar.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "radar.py", line 3, in <module>
    import BFV
  File "C:\Program Files (x86)\Origin Games\radar\BFV.py", line 375
    offsets["OBFUS_MGR_PTR_1"]                 = 0x1438B46D0
                                                                                            ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by DJPatron** [comment]
It works! Thank you!
