### ISSUE TITLE
does it still working?

### ISSUE THREAD

**Issue by qiyi71w** [70RMUND/Tormund-BFV-Radar#16]
does it still working?

**Comment by qiyi71w** [comment]
when I run it, it shows severe : exception caught!

**Comment by 1411348064** [comment]
[+] Searching for BFV.exe...
[+]
[+] SEVERE: EXCEPTION CAUGHT!
[+]

Traceback (most recent call last):
  File "Radar.py", line 602, in <module>
    StartRadar() # Start the rest of the radar setup
  File "Radar.py", line 541, in StartRadar
    phandle = BFV.GetHandle()
  File "F:\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\BFV.py", line 469, in GetHandle
    pid = api.get_processid_by_name("bfv.exe")
  File "F:\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\MemAccess.py", line 155, in get_processid_by_name
    if procname.decode("utf-8").lower() == name.lower():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 2: invalid continuation byte

[+]
[+] Exiting Radar...
