### ISSUE TITLE
im getting this error

### ISSUE THREAD

**Issue by iammk19** [70RMUND/Tormund-BFV-Radar#5]
Traceback (most recent call last):
  File "Radar.py", line 602, in <module>
    StartRadar() # Start the rest of the radar setup
  File "Radar.py", line 557, in StartRadar
    BFV.Process(phandle,cnt) # this accesses game memory for data
  File "C:\Users\kazim\Downloads\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\BFV.py", line 652, in Process
    pm = PointerManager(pHandle)
  File "C:\Users\kazim\Downloads\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\BFV.py", line 47, in __init__
    offsets["OBFUS_MGR"] = self.GetObfuscationMgr()
  File "C:\Users\kazim\Downloads\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\BFV.py", line 78, in GetObfuscationMgr
    buf = ss.read()
  File "C:\Users\kazim\Downloads\Tormund-BFV-Radar-master\Tormund-BFV-Radar-master\MemAccess.py", line 670, in read
    cbuff = (c_char * len(self.buffer)).from_buffer(self.buffer)
TypeError: underlying buffer is not writable

**Comment by exelstar12** [comment]
im getting this error too, and im got banned from the host server. idk why

**Comment by 70RMUND** [comment]
If anyone gets this error please post the version of python you are using by entering `python -VV` into your commandline/powershell
