### ISSUE TITLE
radar not working after 17/11/2020 update

### ISSUE THREAD

**Issue by charlee-dev** [70RMUND/Tormund-BFV-Radar#8]
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[+] Tormund's External Radar v1.3 for Battlefield V (Summer Update 2020 P7.1) - June 25, 2020)
[+] Searching for BFV.exe...
[+] BFV.exe found, Handle: 0x24c
[+] Gathering offsets, please wait...
[+] Starting Radar...
[+] Done
[+] Searching for ObfuscationMgr...
[+]
[+] SEVERE: EXCEPTION CAUGHT!
[+]

Traceback (most recent call last):
  File "Radar.py", line 602, in <module>
    StartRadar() # Start the rest of the radar setup
  File "Radar.py", line 557, in StartRadar
    BFV.Process(phandle,cnt) # this accesses game memory for data
  File "E:\Desktop\Tormund-BFV-Radar-master\BFV.py", line 687, in Process
    pm = PointerManager(pHandle)
  File "E:\Desktop\Tormund-BFV-Radar-master\BFV.py", line 62, in __init__
    offsets["OBFUS_MGR"] = self.GetObfuscationMgr()
  File "E:\Desktop\Tormund-BFV-Radar-master\BFV.py", line 93, in GetObfuscationMgr
    buf = ss.read()
  File "E:\Desktop\Tormund-BFV-Radar-master\MemAccess.py", line 670, in read
    cbuff = (c_char * len(self.buffer)).from_buffer(self.buffer)
TypeError: underlying buffer is not writable

[+]
[+] Exiting Radar...

**Comment by DJPatron** [comment]
Same. I think offsets was changed. Should we wait for the fix patiently, mr. Tormund? Do you plan to do it at all?
UPD 20nov2020: It is working good! Thank you!
